const _items = [
  {
    quote: "We're misusing Mainline as a CRM and it still works!",
    author: 'Amy Chase',
    role: 'PM',
    company: 'Mercury Finance',
    image: 'https://deifkwefumgah.cloudfront.net/shadcnblocks/block/mainline/testimonials/amy-chase.webp',
  },
  {
    quote: 'I was able to replace 80% of my team with Mainline bots.',
    author: 'Jonas Kotara',
    role: 'Lead Engineer',
    company: 'Mercury Finance',
    image: 'https://deifkwefumgah.cloudfront.net/shadcnblocks/block/mainline/testimonials/jonas-kotara.webp',
  },
  {
    quote: 'Founder Mode is hard enough without having a really nice PM app.',
    author: 'Kevin Yam',
    role: 'Founder',
    company: 'Mercury Finance',
    image: 'https://deifkwefumgah.cloudfront.net/shadcnblocks/block/mainline/testimonials/kevin-yam.webp',
  },
  {
    quote: 'I can use the tool as a substitute from my PM.',
    author: 'Kundo Marta',
    role: 'Founder',
    company: 'Mercury Finance',
    image: 'https://deifkwefumgah.cloudfront.net/shadcnblocks/block/mainline/testimonials/kundo-marta.webp',
  },
  {
    quote: "We're misusing Mainline as a CRM and it still works!",
    author: 'Amy Chase',
    role: 'PM',
    company: 'Mercury Finance',
    image: 'https://deifkwefumgah.cloudfront.net/shadcnblocks/block/mainline/testimonials/amy-chase.webp',
  },
  {
    quote: 'I was able to replace 80% of my team with Mainline bots.',
    author: 'Jonas Kotara',
    role: 'Lead Engineer',
    company: 'Mercury Finance',
    image: 'https://deifkwefumgah.cloudfront.net/shadcnblocks/block/mainline/testimonials/jonas-kotara.webp',
  },
  {
    quote: 'Founder Mode is hard enough without having a really nice PM app.',
    author: 'Kevin Yam',
    role: 'Founder',
    company: 'Mercury Finance',
    image: 'https://deifkwefumgah.cloudfront.net/shadcnblocks/block/mainline/testimonials/kevin-yam.webp',
  },
  {
    quote: 'I can use the tool as a substitute from my PM.',
    author: 'Kundo Marta',
    role: 'Founder',
    company: 'Mercury Finance',
    image: 'https://deifkwefumgah.cloudfront.net/shadcnblocks/block/mainline/testimonials/kundo-marta.webp',
  },
];
