#!/usr/bin/env sh
echo "🔥 Running pre-push checks..."

# Run npm install
# echo "📦 Installing dependencies..."
# npm i
INSTALL_EXIT_CODE=$?

if [ $INSTALL_EXIT_CODE -ne 0 ]; then
  echo ""
  echo "❌❌❌ NPM INSTALL FAILED WITH CODE $INSTALL_EXIT_CODE ❌❌❌"
  echo "❌❌❌ PUSH ABORTED ❌❌❌"
  echo ""
  # Force exit with unmistakable error
  exec < /dev/null
  exit 128
fi
while read local_ref local_sha remote_ref remote_sha
do
  # Extract branch names from refs/heads/branch-name
  local_branch=${local_ref#refs/heads/}
  remote_branch=${remote_ref#refs/heads/}

  # Run migrations locally to fix before breaking the ci.
  # if [ "$remote_branch" = "master" ]; then
    #npm run db:migrate </dev/tty
  # fi
done

git add .
echo "✅ All checks passed! Pushing to remote..."